# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('F', 'Кормление'), ('FF', 'Принудительное кормление'), ('RF', 'Отказ от корма'), ('R', 'Срыг'), ('S', 'Линька'), ('SB', 'Проблемная линька'), ('HP', 'Проблемы со здоровьем'), ('HC', 'Ветеринарные процедуры'), ('B', 'Зимовка'), ('C', 'Спаривание'), ('L', 'Откладка яиц'), ('D', 'Смерть'), ('O', 'Другое')], default='F', max_length=2, verbose_name='Событие')),
                ('event_date', models.DateField(verbose_name='Дата')),
                ('event_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('reminde_me', models.DateField(blank=True, null=True, verbose_name='Напомнить мне')),
                ('reminder_comment', models.TextField(blank=True, verbose_name='Текст напоминания')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'verbose_name': 'Event',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=20, verbose_name='Имя питомца')),
                ('morph', models.CharField(blank=True, max_length=50, verbose_name='Морфа')),
                ('gender', models.CharField(choices=[('0', 'Неизвестно'), ('1', 'Самец'), ('2', 'Самка')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.IntegerField(blank=True, null=True, verbose_name='Дата рождения')),
                ('birth_month', models.IntegerField(blank=True, null=True, verbose_name='Месяц рождения')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('fed_freq', models.IntegerField(null=True, verbose_name='Частота кормления')),
                ('pet_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_dead', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pets',
                'verbose_name': 'Pet',
                'ordering': ['pet_name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=20, verbose_name='Род')),
                ('species', models.CharField(max_length=20, verbose_name='Вид')),
                ('suspecies', models.CharField(blank=True, max_length=20, verbose_name='Подвид')),
            ],
            options={
                'verbose_name_plural': 'Species',
                'verbose_name': 'Species',
                'ordering': ['genus', 'species', 'suspecies'],
            },
        ),
        migrations.AddField(
            model_name='pets',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='keepers', to='pets.Species', verbose_name='Вид животного'),
        ),
        migrations.AddField(
            model_name='pets',
            name='u_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pets'),
        ),
    ]
