# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='fed_freq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Частота кормления'),
        ),
    ]
